name: CI

on:
    push:
        branches: [ main ]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    phpstan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'

            - name: Install Composer packages
              uses: ramsey/composer-install@v3

            - name: Run PHPStan
              run: vendor/bin/phpstan --ansi
