name: CI

on:
    push:
        branches: [ main ]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3', '8.4' ]
                dependency-versions: [ lowest, highest ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '${{ matrix.php }}'
                    coverage: none

            -   name: Install Composer packages
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: '${{ matrix.dependency-versions }}'

            -   name: Run tests
                run: vendor/bin/phpunit --colors=always

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            -   name: Install Composer packages
                uses: ramsey/composer-install@v3
                with:
                    dependency-versions: '${{ matrix.dependency-versions }}'

            -   name: Run PHPStan
                run: vendor/bin/phpstan --ansi
